# GitHub Funding Configuration
# Configure your sponsor button with the platforms below

# GitHub Sponsors (up to 4 usernames)
# github: [username1, username2, username3, username4]
github: DevYukis

# Patreon
# patreon: username

# Open Collective
# open_collective: username

# Ko-fi
ko_fi: devyuki

# Tidelift (format: platform-name/package-name)
# tidelift: npm/package-name
# tidelift: pypi/package-name
# tidelift: rubygems/package-name

# Community Bridge / LFX Mentorship
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Otechie
# otechie: username

# Polar
# polar: username

# Buy Me a Coffee
# buy_me_a_coffee: username

# Thanks.dev
# thanks_dev: u/gh/username

# Custom URLs (up to 4 custom links)
# custom: https://www.paypal.me/username
# custom: ["https://www.paypal.me/username", "https://example.com/donate"]
